-- 코드를 입력하세요
SELECT U.BOARD_ID, U.WRITER_ID, U.TITLE, U.PRICE, 
CASE
    WHEN U.STATUS = 'DONE' THEN '거래완료'
    WHEN U.STATUS = 'SALE' THEN '판매중'
    ELSE '예약중'    
END AS STATUS
FROM USED_GOODS_BOARD AS U WHERE U.CREATED_DATE = '2022-10-05' ORDER BY BOARD_ID DESC;