-- 코드를 입력하세요
-- SQL 문자열 결합 함수는 CONCAT을 사용할 수 있다.
-- WHERE 절에서는 MAX 등의 집계 함수를 직접적으로 사용할 수 없다.
-- SELECT로 MAX 뽑아내자
SELECT 
CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME , F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F
INNER JOIN USED_GOODS_BOARD AS B 
ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;
